Repository madeline-scyphers/boa, pull requests merged in 2023-02, with the labels that each got.

#82 Bugfix: pin sqlalchemy
  docs/user_guide/getting_started.rst
  docs/user_guide/package_overview.rst
  environment.yml
  environment_mac_x86.yml
Labels: bug, package

#91 Add a Code of Conduct based on contributor covenant
  CODE_OF_CONDUCT.md
Labels: package

#89 Add information and example of language agnostic interface
  CODE_OF_CONDUCT.md
  boa/wrappers/__init__.py
  boa/wrappers/script_wrapper.py
  docs/user_guide/package_overview.rst
  docs/user_guide/run_script.rst
  tests/scripts/other_langs/r_package_full/config.yaml
  tests/scripts/other_langs/r_package_full/fetch_trial_data.R
  tests/scripts/other_langs/r_package_full/run_model.R
  tests/scripts/other_langs/r_package_full/set_trial_status.R
  tests/scripts/other_langs/r_package_full/write_configs.R
  tests/scripts/other_langs/r_package_light/config.yaml
  tests/scripts/other_langs/r_package_light/run_model.R
  tests/scripts/other_langs/r_package_streamlined/config.yaml
  tests/scripts/other_langs/r_package_streamlined/config_fail.yaml
  tests/scripts/other_langs/r_package_streamlined/run_model.R
  tests/scripts/other_langs/r_utils/hartman6.R
Labels: documentation

#94 Add DOI badge to README
  README.md
Labels: package
